spring.application.name=college_event_web
server.port=8084
management.endpoints.web.exposure.include=*

# Official Spring Boot Actuator settings for StatsD
management.metrics.export.statsd.enabled=true
management.metrics.export.statsd.host=graphite
management.metrics.export.statsd.port=8125
management.metrics.export.statsd.flavor=etsy
management.metrics.export.statsd.step=10s
management.metrics.tags.application=college-event-web