spring.application.name=college_event_web
server.port=8084

# Official Spring Boot Actuator settings for Graphite
management.graphite.metrics.export.enabled=true
management.graphite.metrics.export.host=graphite
management.graphite.metrics.export.port=8125
management.graphite.metrics.export.protocol=UDP

# How often to push metrics (e.g., every 1 minute)
management.graphite.metrics.export.step=1m

# Tag the metrics so you can find them in Grafana
management.metrics.tags.application=TechSympApp