apiVersion: apps/v1
kind: Deployment
metadata:
  name: techsymp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techsymp-web
  template:
    metadata:
      labels:
        app: techsymp-web
    spec:
      containers:
      - name: techsymp-container
        # Must match the exact tag you just built!
        image: college-event-web:v1
        # CRITICAL for local testing: Tells K8s not to look on Docker Hub for the image
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8084