apiVersion: v1
kind: Service
metadata:
  name: techsymp-service
spec:
  # NodePort makes it easily accessible on your local machine
  type: NodePort
  selector:
    app: techsymp-web
  ports:
    - port: 80          # The port K8s exposes internally
      targetPort: 8084  # The port your Spring Boot app is actually running on
      nodePort: 30084   # The permanent port you will type in your browser